[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node src/cms/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# IMPORTANT: Railway persistent volume configuration
# Volume setup in Railway dashboard:
# 1. Go to your Railway project dashboard
# 2. Click on your service
# 3. Go to "Settings" > "Volumes"
# 4. Add volume with Mount path = /data
# 5. Update DATABASE_PATH environment variable = /data/cms.db
#
# This keeps the database persistent between deployments
# The code files (init.js, migrate.js, schema.sql) are deployed with the app
# Only the actual database file (cms.db) lives on the volume